### ISSUE TITLE
Can't make it work. cldCDP.launch() - Error.

### ISSUE THREAD

**Issue by XaverKupfer** [PerditionC/VBAChromeDevProtocol#2]
Haven't been able to make any of the examples of Examples.xlsm work.

Using Windows 10 and 64-bit Excel.

Any of them finish with this immediate window message:

-----
Failed to write CDP message!
{"method":"Target.setDiscoverTargets","params":{"discover":true}, "id":2} 
-----
cldCDP.launch() - Error: Error defined by application or object
-----

When all browsers are closed, nothing happens (only the mentioned immediate window message). 
When only Chrome or only Edge is running, no other browser starts and only the mentioned immediate window message appears.
When Chrome and Edge are running, FireFox starts and finally the mentioned immediate window message appears.

**Comment by PerditionC** [comment]
What is the full path to the browser?  My guess is the hard coded paths aren't correct.   Additional debug messages may need to be added, but let me know so we can check the easy possible cause first.

**Comment by XaverKupfer** [comment]
You found it!

CDP Addin.xlam _ browsers module :


Private Const pathEdge As String = "C:\Program Files(x86)\Microsoft\Edge\Application\"
Private Const pathChrome As String = "C:\Program Files(x86)\Google\Chrome\Application\"
Private Const pathFirefox As String = "C:\Program Files\Mozilla Firefox\"
-----
I changed them to the actual paths and everything looks to work like a charm!.

Thank you!
