### ISSUE TITLE
Browser paths

### ISSUE THREAD

**Issue by PerditionC** [PerditionC/VBAChromeDevProtocol#3]
Browser paths need to be queried for instead of using hard coded paths.  Different installs may and do use different paths.

**Comment by moaoci** [comment]
Hello,  I worked a solution for the hardcoded paths together with an enhancement to easily pass additionnal inline commands to the browser.  I also added a switch to force killing of existing browser without a prompt.  This is my first contribution to GitHub.  If I understand, my next step would be to start with a pull request and submit my code.   I know how to test VBA in Excel but not with GitHub.

**Comment by PerditionC** [comment]
Please export the VBA [class] module(s) from Excel and make a pull request against the corresponding files in the src/ directory.  After review and merge I will commit a new version of the Excel files in dist/ directory.  Most of my testing is also in Excel, I just export the modules as text to allow diff'ing and usage with git.  Thank you.

**Comment by moaoci** [comment]
When I upload my files, there is a choice for commit directly to main branch or create a new branch... Which one is best ?

**Comment by PerditionC** [comment]
You can use the main branch.  For other projects, a topic branch may be the better option, but for this project that is just unnecessary complication.

**Comment by moaoci** [comment]
I can't figure out how to undo commit or refresh my fork with the main branch...

**Comment by PerditionC** [comment]
PR with implementation merged.  Thank you.
