### ISSUE TITLE
Enhance browser selection and enable additional inlineCommands

### ISSUE THREAD

**Issue by moaoci** [PerditionC/VBAChromeDevProtocol#9]
To better control which browser to launch (without changing LaunchBrowser default logic).

Add two parameters 
    additionalInlineCommands 
    killWithoutAsking  

Allow these parameters and whichBrowser to follow thru the whole sequence AutomateBrowser.Launch, clsCDP.Launch and Browsers.LaunchBrowser  

Create functions to choose browserType outside of LaunchBrowser preset order
      getFirstAvailableBrowser (browser1, browser2, browser3)  that will get the first non running installed browser
      getFirstInstalledBrowser (browser1,browser2,browser3)

Add noBrowser to browserType enumeration

Show / document examples in examples.xlam

**Comment by PerditionC** [comment]
Pull Request with implementation merged, closing.
